-----------------------
-- Up
-----------------------

INSERT INTO entries VALUES(1,'Richard Stallman');
INSERT INTO entries VALUES(2,'Linus Torvalds');
INSERT INTO entries VALUES(3,'Steve Wozniak');
INSERT INTO entries VALUES(4,'Ada Lovelace');
INSERT INTO entries VALUES(5,'Mark Zuckerberg');
INSERT INTO entries VALUES(6,'Bill Gates');
INSERT INTO entries VALUES(7,'Aaron Swartz');
INSERT INTO entries VALUES(8,'Ken Thompson');
INSERT INTO entries VALUES(9,'Dennis Ritchie');
INSERT INTO entries VALUES(10,'Guido van Rossum');
INSERT INTO entries VALUES(11,'Larry Page');
INSERT INTO entries VALUES(12,'Sergey Brin');
INSERT INTO entries VALUES(13,'Edsger W. Dijkstra');
INSERT INTO entries VALUES(14,'John D. Carmack');
INSERT INTO entries VALUES(15,'Markus Persson');
INSERT INTO entries VALUES(16,'Tim Schafer');
INSERT INTO entries VALUES(17,'Sid Meier');
INSERT INTO entries VALUES(18,'Hideo Kojima');
INSERT INTO entries VALUES(19,'Shigeru Miyamoto');
INSERT INTO entries VALUES(20,'Steve Ballmer');
INSERT INTO entries VALUES(21,'Monty Python and the Holy Grail');
INSERT INTO entries VALUES(22,'Memory');
INSERT INTO entries VALUES(23,'SSD');
INSERT INTO entries VALUES(24,'Graphics Card');
INSERT INTO entries VALUES(25,'HDD');
INSERT INTO entries VALUES(26,'Western Digital');
INSERT INTO entries VALUES(27,'CPU');
INSERT INTO entries VALUES(28,'Bus');
INSERT INTO entries VALUES(29,'Floppy Drive');
INSERT INTO entries VALUES(30,'Printer');
INSERT INTO entries VALUES(31,'L1 Cache');
INSERT INTO entries VALUES(32,'tar xzf');
INSERT INTO entries VALUES(33,'tar czf');
INSERT INTO entries VALUES(34,'tar xJf');
INSERT INTO entries VALUES(35,'chmod 777');
INSERT INTO entries VALUES(36,'chmod 644');
INSERT INTO entries VALUES(37,'lsof');
INSERT INTO entries VALUES(38,'wget');
INSERT INTO entries VALUES(39,'rm -rf /');
INSERT INTO entries VALUES(40,'please');
INSERT INTO entries VALUES(41,'ln -s');
INSERT INTO entries VALUES(42,'Matrix');
INSERT INTO entries VALUES(43,'Lord of the Rings');
INSERT INTO entries VALUES(44,'Interview with the Vampire');
INSERT INTO entries VALUES(45,'Requiem for a Dream');
INSERT INTO entries VALUES(46,'Zelda');
INSERT INTO entries VALUES(47,'Pac-Man');
INSERT INTO entries VALUES(48,'Metal Gear Solid');
INSERT INTO entries VALUES(49,'Half Life');
INSERT INTO entries VALUES(50,'Mass Effect');
INSERT INTO entries VALUES(51,'Skyrim');
INSERT INTO entries VALUES(52,'Tetris');
INSERT INTO entries VALUES(53,'Portal');
INSERT INTO entries VALUES(54,'Civilization');
INSERT INTO entries VALUES(55,'Stronghold');
INSERT INTO entries VALUES(56,'Minecraft');
INSERT INTO entries VALUES(57,'Candy Crush');
INSERT INTO entries VALUES(58,'Minesweeper');
INSERT INTO entries VALUES(59,'SSH');
INSERT INTO entries VALUES(60,'HTTP');
INSERT INTO entries VALUES(61,'HTTPS');
INSERT INTO entries VALUES(62,'FTP');
INSERT INTO entries VALUES(63,'TCP');
INSERT INTO entries VALUES(64,'UDP');
INSERT INTO entries VALUES(65,'SFTP');
INSERT INTO entries VALUES(66,'Telnet');
INSERT INTO entries VALUES(67,'Stephanie');
INSERT INTO entries VALUES(68,'Russ');
INSERT INTO entries VALUES(69,'Bron');
INSERT INTO entries VALUES(71,'Black Mamba');
INSERT INTO entries VALUES(72,'Cupcake');
INSERT INTO entries VALUES(78,'The Godfather');
INSERT INTO entries VALUES(79,'Titanic');
INSERT INTO entries VALUES(80,'Fight Club');
INSERT INTO entries VALUES(81,'Pulp Fiction');
INSERT INTO entries VALUES(82,'Junglebook');
INSERT INTO entries VALUES(83,'The Lion King');
INSERT INTO entries VALUES(84,'Indiana Jones');
INSERT INTO entries VALUES(85,'James Bond');
INSERT INTO entries VALUES(86,'Austin Powers');
INSERT INTO entries VALUES(87,'Braveheart');
INSERT INTO entries VALUES(88,'Space Odysee');
INSERT INTO entries VALUES(89,'Back to the Future');
INSERT INTO entries VALUES(90,'The Shining');
INSERT INTO entries VALUES(91,'The Ring');
INSERT INTO entries VALUES(92,'Reservoir Dogs');
INSERT INTO entries VALUES(93,'Trainspotting');
INSERT INTO entries VALUES(94,'Microsoft');
INSERT INTO entries VALUES(95,'Mc Donalds');
INSERT INTO entries VALUES(96,'Coca Cola');
INSERT INTO entries VALUES(97,'Uber');
INSERT INTO entries VALUES(98,'Telegram');
INSERT INTO entries VALUES(99,'Dropbox');
INSERT INTO entries VALUES(100,'Oracle');
INSERT INTO entries VALUES(101,'Kentucky Fried Chicken');
INSERT INTO entries VALUES(102,'Siemens');
INSERT INTO entries VALUES(103,'Samsung');
INSERT INTO entries VALUES(104,'Blackberry');
INSERT INTO entries VALUES(105,'Apple');
INSERT INTO entries VALUES(106,'HTC');
INSERT INTO entries VALUES(107,'OnePlus');
INSERT INTO entries VALUES(108,'Nokia');
INSERT INTO entries VALUES(109,'Huawei');
INSERT INTO entries VALUES(110,'Sony');
INSERT INTO entries VALUES(111,'Nestlé');
INSERT INTO entries VALUES(112,'Play Boy');
INSERT INTO entries VALUES(113,'Youtube');
INSERT INTO entries VALUES(114,'Google');
INSERT INTO entries VALUES(115,'GitHub');
INSERT INTO entries VALUES(116,'Reddit');
INSERT INTO entries VALUES(117,'Wikipedia');
INSERT INTO entries VALUES(118,'ubat-game');
INSERT INTO entries VALUES(119,'Chefkoch');
INSERT INTO entries VALUES(120,'Baidu');
INSERT INTO entries VALUES(121,'Amazon');
INSERT INTO entries VALUES(122,'Twitter');
INSERT INTO entries VALUES(123,'LinkedIn');
INSERT INTO entries VALUES(124,'Ebay');
INSERT INTO entries VALUES(125,'PornHub');
INSERT INTO entries VALUES(126,'Tumblr');
INSERT INTO entries VALUES(127,'Phosphor');
INSERT INTO entries VALUES(128,'Hydrogen');
INSERT INTO entries VALUES(129,'Carbon');
INSERT INTO entries VALUES(130,'Chlorine');
INSERT INTO entries VALUES(131,'Iron');
INSERT INTO entries VALUES(132,'Iodine');
INSERT INTO entries VALUES(133,'Mercury');
INSERT INTO entries VALUES(134,'Helium');
INSERT INTO entries VALUES(135,'Nitrogen');
INSERT INTO entries VALUES(136,'Neon');
INSERT INTO entries VALUES(137,'Norway');
INSERT INTO entries VALUES(138,'Germany');
INSERT INTO entries VALUES(139,'Jamaica');
INSERT INTO entries VALUES(140,'Cuba');
INSERT INTO entries VALUES(141,'France');
INSERT INTO entries VALUES(142,'Russia');
INSERT INTO entries VALUES(143,'United States of America');
INSERT INTO entries VALUES(144,'Ukraine');
INSERT INTO entries VALUES(145,'New Zealand');
INSERT INTO entries VALUES(146,'Japan');
INSERT INTO entries VALUES(147,'Brazil');
INSERT INTO entries VALUES(148,'Mexico');
INSERT INTO entries VALUES(149,'India');
INSERT INTO entries VALUES(150,'Agypt');
INSERT INTO entries VALUES(151,'South Africa');
INSERT INTO entries VALUES(152,'Haribo');
INSERT INTO entries VALUES(153,'Monsanto');
INSERT INTO entries VALUES(154,'Barbie');
INSERT INTO entries VALUES(155,'Tesla');
INSERT INTO entries VALUES(156,'VW');
INSERT INTO entries VALUES(157,'Porsche');
INSERT INTO entries VALUES(158,'Hummer');
INSERT INTO entries VALUES(159,'Renault');
INSERT INTO entries VALUES(160,'Citroën');
INSERT INTO entries VALUES(161,'Peugeot');
INSERT INTO entries VALUES(162,'Daimler');
INSERT INTO entries VALUES(163,'BMW');
INSERT INTO entries VALUES(164,'Mercedes-Benz');
INSERT INTO entries VALUES(165,'Audi');
INSERT INTO entries VALUES(166,'Alfa Romeo');
INSERT INTO entries VALUES(167,'Ferrari');
INSERT INTO entries VALUES(168,'Fiat');
INSERT INTO entries VALUES(169,'Maserati');
INSERT INTO entries VALUES(170,'Lamborghini');
INSERT INTO entries VALUES(171,'Honda');
INSERT INTO entries VALUES(172,'Mazda');
INSERT INTO entries VALUES(173,'Nissan');
INSERT INTO entries VALUES(174,'Yamaha');
INSERT INTO entries VALUES(175,'Yahoo');
INSERT INTO entries VALUES(176,'Emirates');
INSERT INTO entries VALUES(177,'The Trump Organization');
INSERT INTO entries VALUES(178,'Texas Instruments');
INSERT INTO entries VALUES(179,'Steam');
INSERT INTO entries VALUES(180,'Walmart');
INSERT INTO entries VALUES(181,'Warner Bros.');
INSERT INTO entries VALUES(182,'Thirty Years'' War (1618)');
INSERT INTO entries VALUES(183,'Stab-in-the-back myth (1918)');
INSERT INTO entries VALUES(184,'Fall of the Berlin Wall (1990)');
INSERT INTO entries VALUES(185,'Introduction of the Deutsche Mark (1948)');
INSERT INTO entries VALUES(186,'Konrad Zuse built the Z3 (1941)');
INSERT INTO entries VALUES(187,'Enabling Act, Ermächtigungsgesetz (1933)');
INSERT INTO entries VALUES(188,'German Wirtschaftswunder (1950)');
INSERT INTO entries VALUES(189,'Foundation of the Deutsche Bank (1870)');
INSERT INTO entries VALUES(190,'Construction of the Pyramids of Gizeh (2580–2560 B.C.)');
INSERT INTO entries VALUES(191,'Discovery of Fire (0.2 - 1.7 mio B.C.)');
INSERT INTO entries VALUES(192,'Invention of Democracy (Athen, 508 B.C.)');
INSERT INTO entries VALUES(193,'Brewery of Frist beer (6000 B.C.)');
INSERT INTO entries VALUES(194,'Invention of the Wheel (4000 B.C.)');
INSERT INTO entries VALUES(195,'Destruction of Jericho (7000 B.C.)');
INSERT INTO entries VALUES(196,'First Date in Mayan Calendar (3113 B.C.)');
INSERT INTO entries VALUES(197,'First Date in Egyptian Calendar (4242 B.C.)');
INSERT INTO entries VALUES(198,'Construction of Stonehenge (2400 B.C.)');
INSERT INTO entries VALUES(199,'Exodus of Moses (1200 B.C.)');
INSERT INTO entries VALUES(200,'Coronation of Solomon, Son of David (961 B.C.)');
INSERT INTO entries VALUES(201,'First Olympic Games (776 B.C.)');
INSERT INTO entries VALUES(202,'Death of Buddha (India, 483 B.C.)');
INSERT INTO entries VALUES(203,'Alexander the Great''s Invation (Egypt, 332 B.C.)');
INSERT INTO entries VALUES(204,'Construction of The Great Wall of China (China, 214-204 B.C.)');
INSERT INTO entries VALUES(205,'Ceasar becomes dictator (Rome, 45 B.C.)');
INSERT INTO entries VALUES(206,'Ceasar is assassinated (Rome, 44 B.C.)');
INSERT INTO entries VALUES(207,'Jesus is Born (Bethlehem, 5 B.C.)');
INSERT INTO entries VALUES(208,'Crucifixion of Jesus (Jerusalem, 5 A.D.)');
INSERT INTO entries VALUES(209,'Establishment of London (43 A.D.)');
INSERT INTO entries VALUES(210,'Great Fire of Rome (64 A.D.)');
INSERT INTO entries VALUES(211,'Muhammad starts writing the Koran (625 A.D.)');
INSERT INTO entries VALUES(212,'First Crusade (1096 A.D.)');
INSERT INTO entries VALUES(213,'Invasions of Mongols (1211 - 1258 A.D.)');
INSERT INTO entries VALUES(214,'First Observation of the Stars with a Telescope (Galileo Galilee, 1609 A.D.)');
INSERT INTO entries VALUES(215,'"The Three Laws of Motion" (Sir Isaac Newton, 1687 A.D.)');
INSERT INTO entries VALUES(216,'Boston Tea Party (Boston, 1773 A.D.)');
INSERT INTO entries VALUES(217,'"General relativity" (Albert Einstein, 1916 A.D.)');
INSERT INTO entries VALUES(218,'Discovery of Penicillin (Albert Alexander Flemming, 1928 A.D.)');
INSERT INTO entries VALUES(219,'Start of World War II (1939)');
INSERT INTO entries VALUES(220,'Assassination of John F. Kennedy (1939)');
INSERT INTO entries VALUES(221,'Gantz');
INSERT INTO entries VALUES(222,'Bleach');
INSERT INTO entries VALUES(223,'One Piece');
INSERT INTO entries VALUES(224,'Naruto');
INSERT INTO entries VALUES(225,'Dragon Ball');
INSERT INTO entries VALUES(226,'Yu-gi-oh!');
INSERT INTO entries VALUES(227,'Beyblade');
INSERT INTO entries VALUES(228,'Fullmetal Alchemist');
INSERT INTO entries VALUES(229,'Gintama');
INSERT INTO entries VALUES(230,'Ranma ½');
INSERT INTO entries VALUES(231,'Digimon');
INSERT INTO entries VALUES(232,'Cowboy Bebop');
INSERT INTO entries VALUES(233,'Fairy Tail');
INSERT INTO entries VALUES(234,'Steins;Gate');
INSERT INTO entries VALUES(235,'Berserk');
INSERT INTO entries VALUES(236,'Pokémon');
INSERT INTO entries VALUES(237,'Attack on Titan');
INSERT INTO entries VALUES(238,'Ghost in the Shell');
INSERT INTO entries VALUES(239,'Elfenlied');
INSERT INTO entries VALUES(240,'Death Note');
INSERT INTO entries VALUES(241,'Hellsing');
INSERT INTO entries VALUES(242,'One Punch Man');
INSERT INTO entries VALUES(243,'Neon Genesis Evangelion');
INSERT INTO entries VALUES(244,'Sword Art Online');
INSERT INTO entries VALUES(245,'Tokyo Ghoul');
INSERT INTO entries VALUES(246,'HunterXHunter');
INSERT INTO entries VALUES(247,'Rick and Morty');
INSERT INTO entries VALUES(248,'Futurama');
INSERT INTO entries VALUES(249,'Regular Show');
INSERT INTO entries VALUES(250,'South Park');
INSERT INTO entries VALUES(251,'Adventure Time');
INSERT INTO entries VALUES(252,'He-Man');
INSERT INTO entries VALUES(253,'Spiderman');
INSERT INTO entries VALUES(254,'The Flintstones');
INSERT INTO entries VALUES(255,'Simpsons');
INSERT INTO entries VALUES(256,'Family Guy');
INSERT INTO entries VALUES(257,'American Dad');
INSERT INTO entries VALUES(258,'Sponge Bob');
INSERT INTO entries VALUES(259,'Tom and Jerry');
INSERT INTO entries VALUES(260,'Micky Mouse');
INSERT INTO entries VALUES(261,'Gravity Falls');
INSERT INTO entries VALUES(262,'SpaceX');
INSERT INTO entries VALUES(263,'Into the Wild');
INSERT INTO entries VALUES(264,'Star Wars');
INSERT INTO entries VALUES(265,'Inception');
INSERT INTO entries VALUES(266,'Pokémon der Film');
INSERT INTO entries VALUES(267,'The Social Network');
INSERT INTO entries VALUES(268,'Batman');
INSERT INTO entries VALUES(269,'Limitless');
INSERT INTO entries VALUES(270,'Finding Nemo');
INSERT INTO entries VALUES(271,'Forrest Gump');
INSERT INTO entries VALUES(272,'GoodFellas');
INSERT INTO entries VALUES(273,'City of God');
INSERT INTO entries VALUES(274,'The Silence of The Lambs');
INSERT INTO entries VALUES(275,'Léon The Professional');
INSERT INTO entries VALUES(276,'Spirited Away');
INSERT INTO entries VALUES(277,'American History X');
INSERT INTO entries VALUES(278,'Interstellar');
INSERT INTO entries VALUES(279,'The Green Mile');
INSERT INTO entries VALUES(280,'Intouchables');
INSERT INTO entries VALUES(281,'Terminator');
INSERT INTO entries VALUES(282,'The Pianist');
INSERT INTO entries VALUES(283,'Schindler''s List');
INSERT INTO entries VALUES(284,'Memento');
INSERT INTO entries VALUES(285,'Apocalypse Now');
INSERT INTO entries VALUES(286,'Prestige');
INSERT INTO entries VALUES(287,'Big Fish');
INSERT INTO entries VALUES(288,'The Lives of Others');
INSERT INTO entries VALUES(289,'Scott Pilgrim');
INSERT INTO entries VALUES(290,'Django Unchained');
INSERT INTO entries VALUES(291,'WALL-E');
INSERT INTO entries VALUES(292,'Alien');
INSERT INTO entries VALUES(293,'Clockwork Orange');
INSERT INTO entries VALUES(294,'Full Metal Jacket');
INSERT INTO entries VALUES(295,'Amadeus');
INSERT INTO entries VALUES(296,'Snatch');
INSERT INTO entries VALUES(297,'The Downfall');
INSERT INTO entries VALUES(298,'99 Francs');
INSERT INTO entries VALUES(299,'Blade Runner');
INSERT INTO entries VALUES(300,'V for Vendetta');
INSERT INTO entries VALUES(301,'The Wolf of Wall Street');
INSERT INTO entries VALUES(302,'The Big Lebowski');
INSERT INTO entries VALUES(303,'Sixth Sense');
INSERT INTO entries VALUES(304,'Kill Bill');
INSERT INTO entries VALUES(305,'Stand by Me');
INSERT INTO entries VALUES(306,'Grand Budapest Hotel');
INSERT INTO entries VALUES(307,'Mad Max');
INSERT INTO entries VALUES(308,'Jurassic Park');
INSERT INTO entries VALUES(309,'The Truman Show');
INSERT INTO entries VALUES(310,'Donnie Darko');
INSERT INTO entries VALUES(311,'12 Monkeys');
INSERT INTO entries VALUES(312,'Jaws');
INSERT INTO entries VALUES(313,'Pirates of the Caribbean');
INSERT INTO tags VALUES(1,'Programmer');
INSERT INTO tags VALUES(2,'Billionaire');
INSERT INTO tags VALUES(3,'Game Designer');
INSERT INTO tags VALUES(4,'Manager');
INSERT INTO tags VALUES(5,'Film');
INSERT INTO tags VALUES(6,'Komödie');
INSERT INTO tags VALUES(7,'Hardware');
INSERT INTO tags VALUES(8,'Linux Command');
INSERT INTO tags VALUES(9,'Movie');
INSERT INTO tags VALUES(10,'Videogame');
INSERT INTO tags VALUES(11,'Application protocol');
INSERT INTO tags VALUES(12,'Comedy');
INSERT INTO tags VALUES(13,'Nerd');
INSERT INTO tags VALUES(14,'NBA Player');
INSERT INTO tags VALUES(15,'wintern');
INSERT INTO tags VALUES(16,'Company');
INSERT INTO tags VALUES(17,'Mobile Phone Company');
INSERT INTO tags VALUES(18,'Website');
INSERT INTO tags VALUES(19,'Chemical Element');
INSERT INTO tags VALUES(20,'Country');
INSERT INTO tags VALUES(21,'Car Company');
INSERT INTO tags VALUES(22,'Historical Event');
INSERT INTO tags VALUES(23,'German Historical Event');
INSERT INTO tags VALUES(24,'Anime');
INSERT INTO tags VALUES(25,'Cartoon');
INSERT INTO entry_tag_map VALUES(1,1);
INSERT INTO entry_tag_map VALUES(2,1);
INSERT INTO entry_tag_map VALUES(3,1);
INSERT INTO entry_tag_map VALUES(4,1);
INSERT INTO entry_tag_map VALUES(5,1);
INSERT INTO entry_tag_map VALUES(5,2);
INSERT INTO entry_tag_map VALUES(5,4);
INSERT INTO entry_tag_map VALUES(6,1);
INSERT INTO entry_tag_map VALUES(6,2);
INSERT INTO entry_tag_map VALUES(6,4);
INSERT INTO entry_tag_map VALUES(7,1);
INSERT INTO entry_tag_map VALUES(8,1);
INSERT INTO entry_tag_map VALUES(9,1);
INSERT INTO entry_tag_map VALUES(10,1);
INSERT INTO entry_tag_map VALUES(11,1);
INSERT INTO entry_tag_map VALUES(11,2);
INSERT INTO entry_tag_map VALUES(12,1);
INSERT INTO entry_tag_map VALUES(12,2);
INSERT INTO entry_tag_map VALUES(13,1);
INSERT INTO entry_tag_map VALUES(14,1);
INSERT INTO entry_tag_map VALUES(14,3);
INSERT INTO entry_tag_map VALUES(15,1);
INSERT INTO entry_tag_map VALUES(15,3);
INSERT INTO entry_tag_map VALUES(16,1);
INSERT INTO entry_tag_map VALUES(16,3);
INSERT INTO entry_tag_map VALUES(17,1);
INSERT INTO entry_tag_map VALUES(17,3);
INSERT INTO entry_tag_map VALUES(18,3);
INSERT INTO entry_tag_map VALUES(19,3);
INSERT INTO entry_tag_map VALUES(20,2);
INSERT INTO entry_tag_map VALUES(20,4);
INSERT INTO entry_tag_map VALUES(21,9);
INSERT INTO entry_tag_map VALUES(21,12);
INSERT INTO entry_tag_map VALUES(22,7);
INSERT INTO entry_tag_map VALUES(23,7);
INSERT INTO entry_tag_map VALUES(24,7);
INSERT INTO entry_tag_map VALUES(25,7);
INSERT INTO entry_tag_map VALUES(26,7);
INSERT INTO entry_tag_map VALUES(27,7);
INSERT INTO entry_tag_map VALUES(28,7);
INSERT INTO entry_tag_map VALUES(29,7);
INSERT INTO entry_tag_map VALUES(30,7);
INSERT INTO entry_tag_map VALUES(31,7);
INSERT INTO entry_tag_map VALUES(32,8);
INSERT INTO entry_tag_map VALUES(33,8);
INSERT INTO entry_tag_map VALUES(34,8);
INSERT INTO entry_tag_map VALUES(35,8);
INSERT INTO entry_tag_map VALUES(36,8);
INSERT INTO entry_tag_map VALUES(37,8);
INSERT INTO entry_tag_map VALUES(38,8);
INSERT INTO entry_tag_map VALUES(39,8);
INSERT INTO entry_tag_map VALUES(40,8);
INSERT INTO entry_tag_map VALUES(41,8);
INSERT INTO entry_tag_map VALUES(42,9);
INSERT INTO entry_tag_map VALUES(43,9);
INSERT INTO entry_tag_map VALUES(44,9);
INSERT INTO entry_tag_map VALUES(45,9);
INSERT INTO entry_tag_map VALUES(46,10);
INSERT INTO entry_tag_map VALUES(47,10);
INSERT INTO entry_tag_map VALUES(48,10);
INSERT INTO entry_tag_map VALUES(49,10);
INSERT INTO entry_tag_map VALUES(50,10);
INSERT INTO entry_tag_map VALUES(51,10);
INSERT INTO entry_tag_map VALUES(52,10);
INSERT INTO entry_tag_map VALUES(53,10);
INSERT INTO entry_tag_map VALUES(54,10);
INSERT INTO entry_tag_map VALUES(55,10);
INSERT INTO entry_tag_map VALUES(56,10);
INSERT INTO entry_tag_map VALUES(57,10);
INSERT INTO entry_tag_map VALUES(58,10);
INSERT INTO entry_tag_map VALUES(59,11);
INSERT INTO entry_tag_map VALUES(60,11);
INSERT INTO entry_tag_map VALUES(61,11);
INSERT INTO entry_tag_map VALUES(62,11);
INSERT INTO entry_tag_map VALUES(63,11);
INSERT INTO entry_tag_map VALUES(64,11);
INSERT INTO entry_tag_map VALUES(65,11);
INSERT INTO entry_tag_map VALUES(66,11);
INSERT INTO entry_tag_map VALUES(67,14);
INSERT INTO entry_tag_map VALUES(68,14);
INSERT INTO entry_tag_map VALUES(69,14);
INSERT INTO entry_tag_map VALUES(71,14);
INSERT INTO entry_tag_map VALUES(72,14);
INSERT INTO entry_tag_map VALUES(78,9);
INSERT INTO entry_tag_map VALUES(79,9);
INSERT INTO entry_tag_map VALUES(80,9);
INSERT INTO entry_tag_map VALUES(81,9);
INSERT INTO entry_tag_map VALUES(82,9);
INSERT INTO entry_tag_map VALUES(83,9);
INSERT INTO entry_tag_map VALUES(84,9);
INSERT INTO entry_tag_map VALUES(85,9);
INSERT INTO entry_tag_map VALUES(86,9);
INSERT INTO entry_tag_map VALUES(87,9);
INSERT INTO entry_tag_map VALUES(88,9);
INSERT INTO entry_tag_map VALUES(89,9);
INSERT INTO entry_tag_map VALUES(90,9);
INSERT INTO entry_tag_map VALUES(91,9);
INSERT INTO entry_tag_map VALUES(92,9);
INSERT INTO entry_tag_map VALUES(93,9);
INSERT INTO entry_tag_map VALUES(94,16);
INSERT INTO entry_tag_map VALUES(95,16);
INSERT INTO entry_tag_map VALUES(96,16);
INSERT INTO entry_tag_map VALUES(97,16);
INSERT INTO entry_tag_map VALUES(98,16);
INSERT INTO entry_tag_map VALUES(99,16);
INSERT INTO entry_tag_map VALUES(100,16);
INSERT INTO entry_tag_map VALUES(101,16);
INSERT INTO entry_tag_map VALUES(102,16);
INSERT INTO entry_tag_map VALUES(103,16);
INSERT INTO entry_tag_map VALUES(103,17);
INSERT INTO entry_tag_map VALUES(104,16);
INSERT INTO entry_tag_map VALUES(105,16);
INSERT INTO entry_tag_map VALUES(105,17);
INSERT INTO entry_tag_map VALUES(106,16);
INSERT INTO entry_tag_map VALUES(106,17);
INSERT INTO entry_tag_map VALUES(107,16);
INSERT INTO entry_tag_map VALUES(107,17);
INSERT INTO entry_tag_map VALUES(108,16);
INSERT INTO entry_tag_map VALUES(108,17);
INSERT INTO entry_tag_map VALUES(109,17);
INSERT INTO entry_tag_map VALUES(110,16);
INSERT INTO entry_tag_map VALUES(111,16);
INSERT INTO entry_tag_map VALUES(112,16);
INSERT INTO entry_tag_map VALUES(113,18);
INSERT INTO entry_tag_map VALUES(114,16);
INSERT INTO entry_tag_map VALUES(114,18);
INSERT INTO entry_tag_map VALUES(115,18);
INSERT INTO entry_tag_map VALUES(116,18);
INSERT INTO entry_tag_map VALUES(117,18);
INSERT INTO entry_tag_map VALUES(118,18);
INSERT INTO entry_tag_map VALUES(119,18);
INSERT INTO entry_tag_map VALUES(120,18);
INSERT INTO entry_tag_map VALUES(121,16);
INSERT INTO entry_tag_map VALUES(121,18);
INSERT INTO entry_tag_map VALUES(122,18);
INSERT INTO entry_tag_map VALUES(123,18);
INSERT INTO entry_tag_map VALUES(124,18);
INSERT INTO entry_tag_map VALUES(125,18);
INSERT INTO entry_tag_map VALUES(126,18);
INSERT INTO entry_tag_map VALUES(127,19);
INSERT INTO entry_tag_map VALUES(128,19);
INSERT INTO entry_tag_map VALUES(129,19);
INSERT INTO entry_tag_map VALUES(130,19);
INSERT INTO entry_tag_map VALUES(131,19);
INSERT INTO entry_tag_map VALUES(132,19);
INSERT INTO entry_tag_map VALUES(133,19);
INSERT INTO entry_tag_map VALUES(134,19);
INSERT INTO entry_tag_map VALUES(135,19);
INSERT INTO entry_tag_map VALUES(136,19);
INSERT INTO entry_tag_map VALUES(137,20);
INSERT INTO entry_tag_map VALUES(138,20);
INSERT INTO entry_tag_map VALUES(139,20);
INSERT INTO entry_tag_map VALUES(140,20);
INSERT INTO entry_tag_map VALUES(141,20);
INSERT INTO entry_tag_map VALUES(142,20);
INSERT INTO entry_tag_map VALUES(143,20);
INSERT INTO entry_tag_map VALUES(144,20);
INSERT INTO entry_tag_map VALUES(145,20);
INSERT INTO entry_tag_map VALUES(146,20);
INSERT INTO entry_tag_map VALUES(147,20);
INSERT INTO entry_tag_map VALUES(148,20);
INSERT INTO entry_tag_map VALUES(149,20);
INSERT INTO entry_tag_map VALUES(150,20);
INSERT INTO entry_tag_map VALUES(151,20);
INSERT INTO entry_tag_map VALUES(152,16);
INSERT INTO entry_tag_map VALUES(153,16);
INSERT INTO entry_tag_map VALUES(154,16);
INSERT INTO entry_tag_map VALUES(155,16);
INSERT INTO entry_tag_map VALUES(155,21);
INSERT INTO entry_tag_map VALUES(156,21);
INSERT INTO entry_tag_map VALUES(157,21);
INSERT INTO entry_tag_map VALUES(158,21);
INSERT INTO entry_tag_map VALUES(159,21);
INSERT INTO entry_tag_map VALUES(160,21);
INSERT INTO entry_tag_map VALUES(161,21);
INSERT INTO entry_tag_map VALUES(162,21);
INSERT INTO entry_tag_map VALUES(163,21);
INSERT INTO entry_tag_map VALUES(164,21);
INSERT INTO entry_tag_map VALUES(165,21);
INSERT INTO entry_tag_map VALUES(166,21);
INSERT INTO entry_tag_map VALUES(167,21);
INSERT INTO entry_tag_map VALUES(168,21);
INSERT INTO entry_tag_map VALUES(169,21);
INSERT INTO entry_tag_map VALUES(170,21);
INSERT INTO entry_tag_map VALUES(171,21);
INSERT INTO entry_tag_map VALUES(172,21);
INSERT INTO entry_tag_map VALUES(173,21);
INSERT INTO entry_tag_map VALUES(174,21);
INSERT INTO entry_tag_map VALUES(175,16);
INSERT INTO entry_tag_map VALUES(175,18);
INSERT INTO entry_tag_map VALUES(176,16);
INSERT INTO entry_tag_map VALUES(177,16);
INSERT INTO entry_tag_map VALUES(178,16);
INSERT INTO entry_tag_map VALUES(179,16);
INSERT INTO entry_tag_map VALUES(180,16);
INSERT INTO entry_tag_map VALUES(181,16);
INSERT INTO entry_tag_map VALUES(182,22);
INSERT INTO entry_tag_map VALUES(182,23);
INSERT INTO entry_tag_map VALUES(183,22);
INSERT INTO entry_tag_map VALUES(183,23);
INSERT INTO entry_tag_map VALUES(184,22);
INSERT INTO entry_tag_map VALUES(184,23);
INSERT INTO entry_tag_map VALUES(185,22);
INSERT INTO entry_tag_map VALUES(185,23);
INSERT INTO entry_tag_map VALUES(186,22);
INSERT INTO entry_tag_map VALUES(186,23);
INSERT INTO entry_tag_map VALUES(187,22);
INSERT INTO entry_tag_map VALUES(187,23);
INSERT INTO entry_tag_map VALUES(188,22);
INSERT INTO entry_tag_map VALUES(188,23);
INSERT INTO entry_tag_map VALUES(189,22);
INSERT INTO entry_tag_map VALUES(189,23);
INSERT INTO entry_tag_map VALUES(190,22);
INSERT INTO entry_tag_map VALUES(191,22);
INSERT INTO entry_tag_map VALUES(192,22);
INSERT INTO entry_tag_map VALUES(193,22);
INSERT INTO entry_tag_map VALUES(194,22);
INSERT INTO entry_tag_map VALUES(195,22);
INSERT INTO entry_tag_map VALUES(196,22);
INSERT INTO entry_tag_map VALUES(197,22);
INSERT INTO entry_tag_map VALUES(198,22);
INSERT INTO entry_tag_map VALUES(199,22);
INSERT INTO entry_tag_map VALUES(200,22);
INSERT INTO entry_tag_map VALUES(201,22);
INSERT INTO entry_tag_map VALUES(202,22);
INSERT INTO entry_tag_map VALUES(203,22);
INSERT INTO entry_tag_map VALUES(204,22);
INSERT INTO entry_tag_map VALUES(205,22);
INSERT INTO entry_tag_map VALUES(206,22);
INSERT INTO entry_tag_map VALUES(207,22);
INSERT INTO entry_tag_map VALUES(208,22);
INSERT INTO entry_tag_map VALUES(209,22);
INSERT INTO entry_tag_map VALUES(210,22);
INSERT INTO entry_tag_map VALUES(211,22);
INSERT INTO entry_tag_map VALUES(212,22);
INSERT INTO entry_tag_map VALUES(213,22);
INSERT INTO entry_tag_map VALUES(214,22);
INSERT INTO entry_tag_map VALUES(215,22);
INSERT INTO entry_tag_map VALUES(216,22);
INSERT INTO entry_tag_map VALUES(217,22);
INSERT INTO entry_tag_map VALUES(218,22);
INSERT INTO entry_tag_map VALUES(219,22);
INSERT INTO entry_tag_map VALUES(219,23);
INSERT INTO entry_tag_map VALUES(220,22);
INSERT INTO entry_tag_map VALUES(221,24);
INSERT INTO entry_tag_map VALUES(222,24);
INSERT INTO entry_tag_map VALUES(223,24);
INSERT INTO entry_tag_map VALUES(224,24);
INSERT INTO entry_tag_map VALUES(225,24);
INSERT INTO entry_tag_map VALUES(226,24);
INSERT INTO entry_tag_map VALUES(227,24);
INSERT INTO entry_tag_map VALUES(228,24);
INSERT INTO entry_tag_map VALUES(229,24);
INSERT INTO entry_tag_map VALUES(230,24);
INSERT INTO entry_tag_map VALUES(231,24);
INSERT INTO entry_tag_map VALUES(232,24);
INSERT INTO entry_tag_map VALUES(233,24);
INSERT INTO entry_tag_map VALUES(234,24);
INSERT INTO entry_tag_map VALUES(235,24);
INSERT INTO entry_tag_map VALUES(236,10);
INSERT INTO entry_tag_map VALUES(236,24);
INSERT INTO entry_tag_map VALUES(237,24);
INSERT INTO entry_tag_map VALUES(238,24);
INSERT INTO entry_tag_map VALUES(239,24);
INSERT INTO entry_tag_map VALUES(240,24);
INSERT INTO entry_tag_map VALUES(241,24);
INSERT INTO entry_tag_map VALUES(242,24);
INSERT INTO entry_tag_map VALUES(243,24);
INSERT INTO entry_tag_map VALUES(244,24);
INSERT INTO entry_tag_map VALUES(245,24);
INSERT INTO entry_tag_map VALUES(246,24);
INSERT INTO entry_tag_map VALUES(247,25);
INSERT INTO entry_tag_map VALUES(248,25);
INSERT INTO entry_tag_map VALUES(249,25);
INSERT INTO entry_tag_map VALUES(250,25);
INSERT INTO entry_tag_map VALUES(251,25);
INSERT INTO entry_tag_map VALUES(252,25);
INSERT INTO entry_tag_map VALUES(253,25);
INSERT INTO entry_tag_map VALUES(254,25);
INSERT INTO entry_tag_map VALUES(255,25);
INSERT INTO entry_tag_map VALUES(256,25);
INSERT INTO entry_tag_map VALUES(257,25);
INSERT INTO entry_tag_map VALUES(258,25);
INSERT INTO entry_tag_map VALUES(259,25);
INSERT INTO entry_tag_map VALUES(260,25);
INSERT INTO entry_tag_map VALUES(261,25);
INSERT INTO entry_tag_map VALUES(262,16);
INSERT INTO entry_tag_map VALUES(263,9);
INSERT INTO entry_tag_map VALUES(264,9);
INSERT INTO entry_tag_map VALUES(265,9);
INSERT INTO entry_tag_map VALUES(266,9);
INSERT INTO entry_tag_map VALUES(267,9);
INSERT INTO entry_tag_map VALUES(268,9);
INSERT INTO entry_tag_map VALUES(269,9);
INSERT INTO entry_tag_map VALUES(270,9);
INSERT INTO entry_tag_map VALUES(271,9);
INSERT INTO entry_tag_map VALUES(272,9);
INSERT INTO entry_tag_map VALUES(273,9);
INSERT INTO entry_tag_map VALUES(274,9);
INSERT INTO entry_tag_map VALUES(275,9);
INSERT INTO entry_tag_map VALUES(276,9);
INSERT INTO entry_tag_map VALUES(277,9);
INSERT INTO entry_tag_map VALUES(278,9);
INSERT INTO entry_tag_map VALUES(279,9);
INSERT INTO entry_tag_map VALUES(280,9);
INSERT INTO entry_tag_map VALUES(281,9);
INSERT INTO entry_tag_map VALUES(282,9);
INSERT INTO entry_tag_map VALUES(283,9);
INSERT INTO entry_tag_map VALUES(284,9);
INSERT INTO entry_tag_map VALUES(285,9);
INSERT INTO entry_tag_map VALUES(286,9);
INSERT INTO entry_tag_map VALUES(287,9);
INSERT INTO entry_tag_map VALUES(288,9);
INSERT INTO entry_tag_map VALUES(289,9);
INSERT INTO entry_tag_map VALUES(290,9);
INSERT INTO entry_tag_map VALUES(291,9);
INSERT INTO entry_tag_map VALUES(292,9);
INSERT INTO entry_tag_map VALUES(293,9);
INSERT INTO entry_tag_map VALUES(294,9);
INSERT INTO entry_tag_map VALUES(295,9);
INSERT INTO entry_tag_map VALUES(296,9);
INSERT INTO entry_tag_map VALUES(297,9);
INSERT INTO entry_tag_map VALUES(298,9);
INSERT INTO entry_tag_map VALUES(299,9);
INSERT INTO entry_tag_map VALUES(300,9);
INSERT INTO entry_tag_map VALUES(301,9);
INSERT INTO entry_tag_map VALUES(302,9);
INSERT INTO entry_tag_map VALUES(303,9);
INSERT INTO entry_tag_map VALUES(304,9);
INSERT INTO entry_tag_map VALUES(305,9);
INSERT INTO entry_tag_map VALUES(306,9);
INSERT INTO entry_tag_map VALUES(307,9);
INSERT INTO entry_tag_map VALUES(308,9);
INSERT INTO entry_tag_map VALUES(309,9);
INSERT INTO entry_tag_map VALUES(310,9);
INSERT INTO entry_tag_map VALUES(311,9);
INSERT INTO entry_tag_map VALUES(312,9);
INSERT INTO entry_tag_map VALUES(313,9);

-----------------------
-- Down
-----------------------

DELETE FROM entry_tag_map;
DELETE FROM entries;
DELETE FROM tags;
